### ISSUE TITLE
Please add 1 continuous env

### ISSUE THREAD

**Issue by bionicles** [seungeunrho/minimalRL#6]
Would it be possible to implement these algorithms in a continuous env like bipedalwalker?

also, SAC is a cool algorithm.

finally it would be wonderful if you posted scores for each algorithm in the readme (so we can compare performance without having to clone and run everything)

my only negative feedback would be, in some places, you use 1 letter only to describe something, when a word would be more clear, and would not add lines. If you want this to be the most clear/simple RL repo, it would be good if readers can more easily understand the algorithm without having to guess "what does this letter mean?"

**Comment by seungeunrho** [comment]
Hi! Thanks for wonderful suggestions.

1. Since most of the algorithms in minimalRL are for discrete action space,  I think it is not that straightforward to add continuous env to the exisiting algorithms. 

2. SAC! I will implement that soon ... (maybe in a month..?)

3. Benchmark Scores. 
I totally agree with you. Measuring scores for algorithms were always at the top of the todo list. 
I will do it, and add that on README.md. Thank you.

4. I thought I used single letter variable only for  s : states, a: action, r: reward, s': next_state
I guess these letters are quite conventional, isn't it..? 
Even in the lectures from David Silver also uses the single letter variables such as (s, a, r, s').

**Comment by seungeunrho** [comment]
Added! Little bit late though... 
Thanx! :)
